// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateHabitInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Priority    int32   `json:"priority"`
	Time        string  `json:"time"`
	Days        []int32 `json:"days"`
}

type Habit struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Description     *string `json:"description,omitempty"`
	Days            []int32 `json:"days"`
	Time            string  `json:"time"`
	Priority        int32   `json:"priority"`
	Streak          int32   `json:"streak"`
	LongestStreak   int32   `json:"longestStreak"`
	LastCompletedAt *string `json:"lastCompletedAt,omitempty"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
	Skipped         bool    `json:"skipped"`
	Completed       bool    `json:"completed"`
}

type Mutation struct {
}

type Query struct {
}

type Session struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type SystemStats struct {
	TotalUsers    int32 `json:"totalUsers"`
	VerifiedUsers int32 `json:"verifiedUsers"`
	LockedUsers   int32 `json:"lockedUsers"`
	AdminUsers    int32 `json:"adminUsers"`
}

type UpdateHabitInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Priority    *int32  `json:"priority,omitempty"`
	Time        *string `json:"time,omitempty"`
	Days        []int32 `json:"days,omitempty"`
}

type UpdateUserInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

type User struct {
	ID            string   `json:"id"`
	Email         string   `json:"email"`
	EmailVerified bool     `json:"emailVerified"`
	FirstName     *string  `json:"firstName,omitempty"`
	LastName      *string  `json:"lastName,omitempty"`
	Role          UserRole `json:"role"`
	Locked        bool     `json:"locked"`
	CreatedAt     string   `json:"createdAt"`
}

type UsersConnection struct {
	Users      []*User `json:"users"`
	TotalCount int32   `json:"totalCount"`
	HasMore    bool    `json:"hasMore"`
}

type UserRole string

const (
	UserRoleUser  UserRole = "USER"
	UserRoleAdmin UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleUser,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleUser, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
